fixtures:
  repositories:
    apache: "https://github.com/puppetlabs/puppetlabs-apache"
    concat: "https://github.com/puppetlabs/puppetlabs-concat"
    cron_core:
      repo: "https://github.com/puppetlabs/puppetlabs-cron_core"
      puppet_version: '>= 6.0.0'
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
    vcsrepo:
      repo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
        # Version 6.0.0 dropped support for Puppet 6
        # TODO: remove specific version selection when we drop support for Puppet 6
      ref: "v5.5.0"
  symlinks:
    dehydrated: "#{source_dir}"
